exports.up = async function (knex) {
  await knex.schema.createTable('offer_letters', (table) => {
    table.uuid('id').primary().defaultTo(knex.raw('gen_random_uuid()'));
    table.uuid('employee_id').references('id').inTable('employees').onDelete('SET NULL');
    table.string('offer_number', 255).notNullable();
    table.string('candidate_name', 255).notNullable();
    table.string('candidate_email', 255);
    table.string('candidate_phone', 50);
    table.text('candidate_address');
    table.string('position', 255).notNullable();
    table.string('department', 255);
    table.date('date_of_joining');
    table.date('offer_date').notNullable().defaultTo(knex.fn.now());
    table.date('expiry_date');
    table.decimal('ctc_amount', 18, 2).defaultTo(0);
    table.decimal('basic_salary', 18, 2).defaultTo(0);
    table.decimal('hra', 18, 2).defaultTo(0);
    table.decimal('conveyance_allowance', 18, 2).defaultTo(0);
    table.decimal('special_allowance', 18, 2).defaultTo(0);
    table.decimal('medical_allowance', 18, 2).defaultTo(0);
    table.decimal('employer_pf', 18, 2).defaultTo(0);
    table.decimal('employer_esi', 18, 2).defaultTo(0);
    table.string('reporting_manager', 255);
    table.string('work_location', 255).defaultTo('Gurgaon');
    table.string('probation_period', 100).defaultTo('6 months');
    table.string('notice_period', 100).defaultTo('30 days');
    table.text('terms_and_conditions');
    table.text('special_conditions');
    table.string('status', 50).defaultTo('Draft');
    table.timestamp('sent_at', { useTz: true });
    table.timestamp('accepted_at', { useTz: true });
    table.timestamps(true, true);
  });
  await knex.schema.createTable('joining_letters', (table) => {
    table.uuid('id').primary().defaultTo(knex.raw('gen_random_uuid()'));
    table.uuid('employee_id').references('id').inTable('employees').onDelete('SET NULL');
    table.string('joining_number', 255).notNullable();
    table.string('employee_name', 255).notNullable();
    table.string('employee_email', 255);
    table.string('employee_phone', 50);
    table.text('employee_address');
    table.string('position', 255).notNullable();
    table.string('department', 255);
    table.date('date_of_joining').notNullable();
    table.date('joining_date').notNullable().defaultTo(knex.fn.now());
    table.string('reporting_to', 255);
    table.string('work_location', 255).defaultTo('Gurgaon');
    table.text('documents_required');
    table.string('reporting_time', 100).defaultTo('10:00 AM');
    table.string('dress_code', 255).defaultTo('Business Casual');
    table.text('special_instructions');
    table.string('status', 50).defaultTo('Draft');
    table.timestamp('sent_at', { useTz: true });
    table.timestamp('acknowledged_at', { useTz: true });
    table.timestamps(true, true);
  });
  await knex.schema.createTable('government_holidays', (table) => {
    table.uuid('id').primary().defaultTo(knex.raw('gen_random_uuid()'));
    table.string('holiday_name', 255).notNullable();
    table.date('holiday_date').notNullable();
    table.string('holiday_type', 100).defaultTo('Gazetted');
    table.string('state', 100).defaultTo('Haryana');
    table.integer('year').notNullable().defaultTo(2026);
    table.boolean('is_active').defaultTo(true);
    table.text('description');
    table.timestamps(true, true);
  });
  await knex.schema.createTable('hr_policies', (table) => {
    table.uuid('id').primary().defaultTo(knex.raw('gen_random_uuid()'));
    table.string('policy_name', 255).notNullable();
    table.string('policy_number', 100);
    table.string('category', 100).notNullable();
    table.text('description');
    table.text('policy_content').notNullable();
    table.date('effective_date');
    table.date('review_date');
    table.string('applicable_to', 100).defaultTo('All Employees');
    table.string('status', 50).defaultTo('Active');
    table.string('version', 20).defaultTo('1.0');
    table.string('approved_by', 255);
    table.boolean('is_mandatory').defaultTo(false);
    table.text('legal_reference');
    table.timestamps(true, true);
  });
};
exports.down = async function (knex) {
  await knex.schema.dropTableIfExists('hr_policies');
  await knex.schema.dropTableIfExists('government_holidays');
  await knex.schema.dropTableIfExists('joining_letters');
  await knex.schema.dropTableIfExists('offer_letters');
};
